name: Gcc Tests

on: [push, pull_request]

jobs:
  docker-qbs:
    name: "Docker Qbs ${{ matrix.image }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: arbmind/qbs-gcc-qt:2.3.1-14-6.7.1
          - image: arbmind/qbs-gcc-qt:1.24.1-12-6.5.0
          - image: arbmind/qbs-gcc-qt:1.22.1-12-6.3.1

    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Build & Test
        run: >-
          docker run --rm -v ${GITHUB_WORKSPACE}:/build -w /build
          ${{ matrix.image }}
          build
          --file /build/verdigris.qbs
          --build-directory /tmp/build
          -p autotest-runner

  linux-qmake:
    name: "${{ matrix.host_system }} QMake Gcc ${{ matrix.gcc_version }} Qt ${{ matrix.qt_version }} ${{ matrix.std_cpp }}"
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - host_system: ubuntu-22.04
            gcc_version: 12
            qt_version: 6.3.0
            qt_arch: gcc_64
            std_cpp: C++20
            experimental: false

          - host_system: ubuntu-22.04
            gcc_version: 12
            qt_version: 6.2.4
            qt_arch: gcc_64
            std_cpp: C++20
            experimental: false

    runs-on: "${{ matrix.host_system }}"
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "${{ matrix.qt_version }}"
          arch: "${{ matrix.qt_arch }}"
          cache: true

      - name: Setup Gcc
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-${{ matrix.gcc_version }}
          find /usr/bin -name "g++*"
          echo $(which g++)
          echo $(which g++-${{ matrix.gcc_version }})
          sudo update-alternatives --install /usr/bin/g++ g++ $(which g++-${{ matrix.gcc_version }}) 90
          g++ --version

      - name: Git Checkout
        uses: actions/checkout@v4

      - run: qmake -r "CONFIG+=${{ matrix.std_cpp }}"
      - run: make -j
      - run: make check
