name: Windows Tests

on: [push, pull_request]

jobs:
  windows-qbs:
    name: "${{ matrix.host_system }} Qbs Qt ${{ matrix.qt_version }} ${{ matrix.qt_arch }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - host_system: windows-2022
            vcvars: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat
            qt_version: "6.9.0"
            qt_arch: win64_msvc2022_64

          - host_system: windows-2022
            vcvars: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat
            qt_version: "6.8.3"
            qt_arch: win64_msvc2022_64

          - host_system: windows-2022
            vcvars: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat
            qt_version: "6.7.3"
            qt_arch: win64_msvc2019_64

          - host_system: windows-2022
            vcvars: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat
            qt_version: "6.5.0"
            qt_arch: win64_msvc2019_64

          - host_system: windows-2022
            vcvars: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat
            qt_version: "6.3.0"
            qt_arch: win64_msvc2019_64

          - host_system: windows-2019
            vcvars: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat
            qt_version: "6.2.4"
            qt_arch: win64_msvc2019_64

    runs-on: "${{ matrix.host_system }}"
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "${{ matrix.qt_version }}"
          arch: "${{ matrix.qt_arch }}"
          cache: true

      - name: Install Qbs
        run: choco install qbs

      - name: Setup Qbs
        run: |
          qbs setup-toolchains --type msvc $(cmd /c '"${{ matrix.vcvars }}" >nul & where cl') msvc
          qbs setup-qt $(cmd /c where qmake) qt
          qbs config profiles.qt.baseProfile msvc
          qbs config defaultProfile qt
          qbs config --list profiles

      - name: Git Checkout
        uses: actions/checkout@v4

      - run: >-
          qbs build
          --file verdigris.qbs
          --build-directory ${env:RUNNER_TEMP}\build
          -p autotest-runner

  windows-qmake:
    name: "${{ matrix.host_system }} QMake Qt ${{ matrix.qt_version }} ${{ matrix.qt_arch }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - host_system: windows-2022
            qt_version: "6.5.0"
            qt_arch: win64_msvc2019_64

          - host_system: windows-2022
            qt_version: "6.3.0"
            qt_arch: win64_msvc2019_64

          - host_system: windows-2019
            qt_version: "6.2.4"
            qt_arch: win64_msvc2019_64

    runs-on: "${{ matrix.host_system }}"
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "${{ matrix.qt_version }}"
          arch: "${{ matrix.qt_arch }}"
          cache: true

      - name: Add msbuild to PATH
        uses: ilammy/msvc-dev-cmd@v1

      - name: Git Checkout
        uses: actions/checkout@v4

      - run: qmake -r
      - run: nmake
      - run: nmake check

  windows-cmake:
    name: "${{ matrix.host_system }} CMake Qt ${{ matrix.qt_version }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - host_system: windows-2022
            qt_version: "6.9.0"
            qt_arch: win64_msvc2022_64
            preset: "msvc"

    runs-on: "${{ matrix.host_system }}"
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "${{ matrix.qt_version }}"
          arch: "${{ matrix.qt_arch }}"
          cache: true

      - name: Setup CMake & Ninja
        uses: lukka/get-cmake@latest

      - name: Install Tools Ninja and mvsc
        uses: ilammy/msvc-dev-cmd@v1

      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Build
        run: cmake -S . --preset "${{ matrix.preset }}"

      - name: Build Debug
        run: cmake --build --preset "${{ matrix.preset }}-debug"

      - name: Build Release
        run: cmake --build --preset "${{ matrix.preset }}-release"

      - name: Test Debug
        run: ctest --preset "test-${{ matrix.preset }}-debug" --output-junit "${{ github.workspace }}\reports\debug.xml"

      - name: Test Release
        run: ctest --preset "test-${{ matrix.preset }}-release" --output-junit "${{ github.workspace }}\reports\release.xml"

      - name: Check
        run: dir "reports"

      - name: Test Report
        uses: dorny/test-reporter@v2
        if: success() || failure()
        with:
          name: ${{ matrix.host_system }} ${{ matrix.preset }} Tests
          path: reports/*.xml
          reporter: java-junit
